"""Streamlit clinical-ops dashboard.

Three pages mirror the Power BI report:

1. Hospital Operations - encounter volume, LOS, readmission, ED throughput.
2. Revenue & Claims     - claim mix, denial rate, $ leakage.
3. Live Vital Signs     - last-24h vitals, anomaly drilldown.

Data source: Synapse `dw` schema via pyodbc. For local development without
Synapse, set `HCDW_DEMO_MODE=1` to load the bundled `demo_data/` Parquet
files (generated by `dashboards/streamlit/build_demo_data.py`).

Run locally:
    streamlit run dashboards/streamlit/app.py
"""
from __future__ import annotations

import os
from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

try:
    import ai_assistant
except Exception:  # pragma: no cover - optional AI deps
    ai_assistant = None
try:
    import egypt_map
except Exception:  # pragma: no cover
    egypt_map = None

try:
    from zoneinfo import ZoneInfo
    CAIRO_TZ = ZoneInfo("Africa/Cairo")
except Exception:  # pragma: no cover - no tzdata; fall back to a fixed offset
    from datetime import timedelta as _td
    from datetime import timezone as _tz
    CAIRO_TZ = _tz(_td(hours=2))


def _to_cairo(series):
    """Convert a UTC datetime series to Egypt (Cairo) local time for display."""
    s = pd.to_datetime(series, errors="coerce")
    try:
        if getattr(s.dt, "tz", None) is None:
            s = s.dt.tz_localize("UTC")
        return s.dt.tz_convert(CAIRO_TZ).dt.tz_localize(None)
    except Exception:  # noqa: BLE001
        return s


def _cairo_now():
    return pd.Timestamp.now(tz=CAIRO_TZ).tz_localize(None)


DEMO_DIR = Path(__file__).resolve().parent / "demo_data"
DEMO_MODE = os.environ.get("HCDW_DEMO_MODE", "0") == "1" or not DEMO_DIR.exists()

st.set_page_config(
    page_title="Healthcare DW — Clinical Intelligence Platform",
    page_icon="🩺",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ---------------------------------------------------------------------------
#   Look & feel — turn the default Streamlit app into a branded web portal.
# ---------------------------------------------------------------------------
st.markdown(
    """
    <style>
      /* Hide the toolbar clutter (deploy button, main menu) + footer, but NEVER
         the whole header: the control that re-opens a COLLAPSED sidebar
         (stExpandSidebarButton) lives inside the header toolbar, so hiding the
         header would trap the sidebar closed with no way to bring it back. */
      [data-testid="stToolbarActions"], [data-testid="stAppDeployButton"],
      [data-testid="stMainMenu"], #MainMenu, footer {display: none !important;}
      header[data-testid="stHeader"] {background: transparent !important;}
      /* No collapsible sidebar: filters + page navigation live in the main body, so
         the (now-empty) sidebar and both of its toggle controls are hidden entirely.
         This removes the whole "sidebar disappeared and won't come back" problem. */
      [data-testid="stSidebar"], [data-testid="stSidebarCollapseButton"],
      [data-testid="stExpandSidebarButton"], [data-testid="stSidebarCollapsedControl"] {
        display: none !important;}
      .block-container {padding-top: 0.8rem; max-width: 1340px;}
      :root {--ink:#0f172a; --muted:#64748b; --line:#e5e9f0; --accent:#1e6fd9; --bg:#f7f9fc;}
      html, body, [class*="css"] {font-family:-apple-system,"Segoe UI",Roboto,
        "Helvetica Neue",Arial,sans-serif; color:var(--ink);}
      .stApp {background:var(--bg);}
      h1 {font-weight:700; font-size:1.5rem; letter-spacing:-.01em; color:var(--ink);}
      h2 {font-weight:650; font-size:1.15rem;}
      h3 {font-weight:650; font-size:1.02rem; color:var(--ink);}
      /* top bar */
      .hc-topbar {display:flex; align-items:center; justify-content:space-between;
        background:#fff; border:1px solid var(--line); border-radius:10px;
        padding:12px 18px; margin-bottom:16px;}
      .hc-topbar .brand {font-weight:700; font-size:1.05rem; color:var(--ink);}
      .hc-topbar .brand b {color:var(--accent);}
      .hc-topbar .sub {color:var(--muted); font-size:.78rem; font-weight:500;}
      .hc-status {font-size:.8rem; color:var(--muted);}
      .hc-dot {height:8px; width:8px; border-radius:50%; display:inline-block; margin-right:6px; vertical-align:middle;}
      .hc-label {text-transform:uppercase; letter-spacing:.08em; font-size:.72rem;
        color:var(--muted); font-weight:700; margin:10px 0 2px 0;}
      /* flat metric cards */
      div[data-testid="stMetric"] {background:#fff; border:1px solid var(--line);
        border-radius:10px; padding:12px 16px;}
      div[data-testid="stMetricLabel"] p {color:var(--muted); font-size:.8rem; font-weight:600;}
      div[data-testid="stMetricValue"] {color:var(--ink); font-weight:700; font-size:1.55rem;}
      /* main-body page navigation (horizontal radio styled as a real tab bar) */
      div[data-testid="stRadio"] [role="radiogroup"] {gap:8px; flex-wrap:wrap;}
      div[data-testid="stRadio"] [role="radiogroup"] > label {background:#fff;
        border:1px solid var(--line); border-radius:8px; padding:7px 16px; margin:0;
        cursor:pointer; transition:background .12s, border-color .12s;}
      div[data-testid="stRadio"] [role="radiogroup"] > label:hover {border-color:var(--accent);}
      /* hide the radio circle so each option reads as a clickable tab */
      div[data-testid="stRadio"] [role="radiogroup"] > label > div:first-child {display:none !important;}
      /* highlight the ACTIVE page so it's obvious where you are */
      div[data-testid="stRadio"] [role="radiogroup"] > label:has(input:checked)
        {background:var(--accent); border-color:var(--accent);}
      div[data-testid="stRadio"] [role="radiogroup"] > label:has(input:checked) p
        {color:#fff !important; font-weight:650;}
      /* the "Pages" navigation caption */
      .hc-nav {font-weight:700; font-size:.92rem; color:var(--ink); margin:2px 0 7px;}
      .hc-nav span {color:var(--muted); font-weight:500; font-size:.8rem;}
      /* panels */
      .hc-panel {background:#fff; border:1px solid var(--line); border-radius:10px; padding:16px 18px;}
    </style>
    """,
    unsafe_allow_html=True,
)


# ---------------------------------------------------------------------------
#   Data access
# ---------------------------------------------------------------------------
@st.cache_resource(show_spinner=False)
def _connect():
    """Synapse connection. Cached at app level.

    Supports two auth modes (set SYNAPSE_AUTH_METHOD env var):
    - "azure_ad" (recommended for production): uses DefaultAzureCredential
      from the azure-identity package. Works with managed identity, az cli,
      environment credentials, etc.
    - "sql" (default / legacy): uses SYNAPSE_USER + SYNAPSE_PASSWORD.
    """
    if os.environ.get("HCDW_DEMO_MODE", "0") == "1":
        return None
    try:
        import pyodbc
    except ImportError:
        return None
    server = os.environ.get("SYNAPSE_SERVER")
    db = os.environ.get("SYNAPSE_DATABASE")
    if not all([server, db]):
        return None

    auth_method = os.environ.get("SYNAPSE_AUTH_METHOD", "sql").lower()

    if auth_method == "azure_ad":
        try:
            import struct
            from azure.identity import DefaultAzureCredential
        except ImportError:
            st.warning("azure-identity not installed; falling back to SQL auth.")
            auth_method = "sql"
        else:
            credential = DefaultAzureCredential()
            token = credential.get_token("https://database.windows.net/.default")
            token_bytes = token.token.encode("UTF-16-LE")
            token_struct = struct.pack(f"<I{len(token_bytes)}s", len(token_bytes), token_bytes)
            conn = pyodbc.connect(
                f"DRIVER={{ODBC Driver 18 for SQL Server}};SERVER={server};DATABASE={db};"
                f"Encrypt=Yes;TrustServerCertificate=No",
                attrs_before={1256: token_struct},
                autocommit=True,
            )
            return conn

    user = os.environ.get("SYNAPSE_USER")
    pwd = os.environ.get("SYNAPSE_PASSWORD")
    if not all([user, pwd]):
        return None
    return pyodbc.connect(
        f"DRIVER={{ODBC Driver 18 for SQL Server}};SERVER={server};DATABASE={db};"
        f"UID={user};PWD={pwd};Encrypt=Yes;TrustServerCertificate=No",
        autocommit=True,
    )


@st.cache_data(ttl=30, show_spinner=False)
def _query(sql: str, params: tuple = ()) -> pd.DataFrame:
    conn = _connect()
    if conn is not None:
        return pd.read_sql(sql, conn, params=params)
    # Demo fallback
    table = sql.split("FROM")[1].split()[0].strip("[]").split(".")[-1]
    f = DEMO_DIR / f"{table}.parquet"
    if not f.exists():
        st.warning(f"Demo dataset {f.name} not found; run build_demo_data.py.")
        return pd.DataFrame()
    return pd.read_parquet(f)


def _kpi(label: str, value, help_text: str | None = None, delta=None) -> None:
    st.metric(label, value, delta=delta, help=help_text)


# Human-readable column names — no more snake_case in the UI.
PRETTY = {
    "minute_start_utc": "Time (Cairo)", "patient_name": "Patient", "patient_id": "Patient ID",
    "hospital_name": "Hospital", "hospital_code": "Code", "hospital_governorate": "Governorate",
    "patient_governorate": "Governorate", "primary_anomaly_kind": "Anomaly", "bed_number": "Bed",
    "device_id": "Device", "heart_rate_avg": "Heart rate", "heart_rate_min": "HR min",
    "heart_rate_max": "HR max", "spo2_avg": "SpO₂ %", "spo2_min": "SpO₂ min", "systolic_avg": "Systolic",
    "diastolic_avg": "Diastolic", "temperature_c_avg": "Temp °C", "temperature_c_max": "Temp max °C",
    "respiratory_rate_avg": "Resp rate", "sample_count": "Samples", "anomaly_event_count": "Anomalies",
    "primary_icd10_code": "ICD-10", "primary_diagnosis": "Diagnosis", "diagnosis_chapter": "Chapter",
    "encounter_class": "Class", "encounter_date": "Date", "length_of_stay_hours": "LOS (h)",
    "total_cost_usd": "Total cost", "avg_cost": "Avg cost", "avg_cost_usd": "Avg cost",
    "payer_name": "Payer", "billed_amount": "Billed", "paid_amount": "Paid", "allowed_amount": "Allowed",
    "denied_amount": "Denied", "status": "Status", "claim_number": "Claim #", "service_date": "Service date",
    "provider_name": "Provider", "provider_specialty": "Specialty", "age_band": "Age band",
    "gender": "Gender", "beds": "Beds", "bed_count": "Beds", "encounters": "Encounters", "count": "Count",
    "claims": "Claims", "denied": "Denied", "denial_pct": "Denial %", "denial": "Denial %",
    "readmit": "Readmission %", "readmission_pct": "Readmission %", "governorate": "Governorate",
    "days_to_decision": "Days to decide", "line_count": "Lines", "layer": "Layer", "t": "Table",
    "object_name": "Object", "rows_written": "Rows", "started_at": "Started", "finished_at": "Finished",
    "n": "Rows",
}


_MONEY_COLS = {"Total cost", "Avg cost", "Billed", "Paid", "Allowed", "Denied"}
_PCT_COLS = {"Denial %", "Readmission %"}


def _show(df, **kw) -> None:
    """Render a dataframe with friendly column names and formatted numbers."""
    d = df.rename(columns=PRETTY)
    cfg = {}
    for c in d.columns:
        try:
            if c in _MONEY_COLS:
                cfg[c] = st.column_config.NumberColumn(c, format="$%.0f")
            elif c in _PCT_COLS:
                cfg[c] = st.column_config.NumberColumn(c, format="%.1f%%")
        except Exception:  # noqa: BLE001
            pass
    st.dataframe(d, width="stretch", hide_index=True, column_config=cfg, **kw)


# ---------------------------------------------------------------------------
#   Filter data (the Hospital / Date widgets render in the main-body bar below)
# ---------------------------------------------------------------------------
hospitals_df = _query("SELECT DISTINCT hospital_name FROM dw.vw_encounter_enriched ORDER BY hospital_name")
hospitals = ["All"] + (hospitals_df["hospital_name"].tolist() if not hospitals_df.empty else [])


# ---------------------------------------------------------------------------
#   Pages
# ---------------------------------------------------------------------------
PAGES = ["Home", "Hospital Operations", "Revenue & Claims", "Live Vital Signs",
         "Egypt Map", "AI Assistant", "System Health"]


def _filter_clause() -> tuple[str, list]:
    bits = []
    params: list = []
    if selected_hospital != "All":
        bits.append("hospital_name = ?")
        params.append(selected_hospital)
    bits.append("encounter_date BETWEEN ? AND ?")
    params.extend([str(from_date), str(to_date)])
    return " AND ".join(bits), params


def page_operations() -> None:
    st.title("Hospital Operations")
    st.caption(f"Window: {from_date} -> {to_date}.  Hospital: {selected_hospital}")

    where, params = _filter_clause()
    enc = _query(f"SELECT * FROM dw.vw_encounter_enriched WHERE {where}", tuple(params))

    if enc.empty:
        st.info("No encounters in the selected window.")
        return

    c1, c2, c3, c4 = st.columns(4)
    with c1:
        _kpi("Encounters", f"{len(enc):,}", "Total encounters in window.")
    with c2:
        ip = enc[enc["is_inpatient"].eq(True)]
        _kpi(
            "Avg LOS (inpatient)",
            f"{ip['length_of_stay_hours'].mean():.1f} h" if not ip.empty else "—",
        )
    with c3:
        readmit = enc["is_readmission_30d"].eq(True).sum()
        denom = enc["is_inpatient"].eq(True).sum()
        _kpi(
            "30d readmission %",
            f"{(readmit / denom * 100):.2f}%" if denom else "—",
        )
    with c4:
        _kpi(
            "ED visits",
            f"{(enc['encounter_class'] == 'emergency').sum():,}",
        )

    left, right = st.columns(2)
    with left:
        st.subheader("Encounter mix by class")
        mix = enc["encounter_class"].value_counts().reset_index()
        mix.columns = ["encounter_class", "count"]
        fig = px.bar(mix, x="encounter_class", y="count", color="encounter_class")
        fig.update_layout(showlegend=False, height=350)
        st.plotly_chart(fig, width="stretch")
    with right:
        st.subheader("Encounters per day")
        ts = enc.groupby("encounter_date").size().reset_index(name="encounters")
        fig = px.line(ts, x="encounter_date", y="encounters")
        fig.update_layout(height=350)
        st.plotly_chart(fig, width="stretch")

    st.subheader("Top 10 diagnoses")
    top_dx = (
        enc.dropna(subset=["primary_diagnosis"])
           .groupby(["primary_icd10_code", "primary_diagnosis"])
           .size().reset_index(name="count")
           .sort_values("count", ascending=False)
           .head(10)
    )
    fig = px.bar(top_dx.sort_values("count"), x="count", y="primary_diagnosis",
                 orientation="h", hover_data=["primary_icd10_code"], text="count")
    fig.update_traces(marker_color="#1e6fd9", textposition="outside")
    fig.update_layout(height=360, margin=dict(l=0, r=0, t=6, b=0), plot_bgcolor="white",
                      paper_bgcolor="white", xaxis_title=None, yaxis_title=None)
    st.plotly_chart(fig, width="stretch", config={"displayModeBar": True})
    st.caption("Hover for the ICD-10 code · drag to zoom · use the toolbar to download.")


def page_revenue() -> None:
    st.title("Revenue & Claims")

    claim_bits = ["service_date BETWEEN ? AND ?"]
    claim_params: list = [str(from_date), str(to_date)]
    if selected_hospital != "All":
        claim_bits.append("hospital_name = ?")
        claim_params.append(selected_hospital)
    claim_where = " AND ".join(claim_bits)
    claims = _query(f"SELECT * FROM dw.vw_claim_enriched WHERE {claim_where}", tuple(claim_params))
    if claims.empty:
        st.info("No claims in the selected window.")
        return

    c1, c2, c3, c4 = st.columns(4)
    with c1:
        _kpi("Total claims", f"{len(claims):,}")
    with c2:
        _kpi("Total billed", f"{claims['billed_amount'].sum():,.0f}")
    with c3:
        _kpi(
            "Denial rate",
            f"{(claims['is_denied'].sum() / len(claims) * 100):.2f}%",
        )
    with c4:
        billed = claims["billed_amount"].sum()
        paid = claims["paid_amount"].sum()
        _kpi(
            "Collection rate",
            f"{(paid / billed * 100):.1f}%" if billed else "—",
            help_text="paid / billed",
        )

    left, right = st.columns(2)
    with left:
        st.subheader("Status mix")
        mix = claims["status"].value_counts().reset_index()
        mix.columns = ["status", "count"]
        mix["status"] = mix["status"].str.replace("_", " ").str.title()
        fig = px.pie(mix, names="status", values="count", hole=0.45)
        fig.update_layout(height=350)
        st.plotly_chart(fig, width="stretch")
    with right:
        st.subheader("Denial rate by payer · click to drill")
        per_payer = (
            claims.groupby("payer_name")
                  .agg(claims=("claim_sk", "count"),
                       denied=("is_denied", "sum"))
                  .assign(denial_pct=lambda d: 100 * d["denied"] / d["claims"])
                  .reset_index()
                  .sort_values("denial_pct", ascending=False)
        )
        fig = px.bar(per_payer, x="payer_name", y="denial_pct",
                     custom_data=["payer_name"], hover_data=["claims", "denied"])
        fig.update_traces(marker_color="#1e6fd9")
        fig.update_layout(height=350, yaxis_title="denial %", plot_bgcolor="white",
                          paper_bgcolor="white", xaxis_title=None)
        pay_evt = st.plotly_chart(fig, width="stretch", on_select="rerun", key="rev_payer")

    picked = None
    try:
        pts = (pay_evt.get("selection", {}) or {}).get("points", []) if isinstance(pay_evt, dict) \
            else getattr(getattr(pay_evt, "selection", None), "points", [])
        if pts:
            cd = pts[0].get("customdata") if isinstance(pts[0], dict) else None
            picked = cd[0] if cd else None
    except Exception:  # noqa: BLE001
        picked = None
    if picked:
        sub = claims[claims["payer_name"] == picked]
        st.markdown(f'<div class="hc-label">Drill-down — {picked}</div>', unsafe_allow_html=True)
        dc = st.columns(4)
        dc[0].metric("Claims", f"{len(sub):,}")
        dc[1].metric("Denial rate", f"{100 * sub['is_denied'].mean():.1f}%")
        dc[2].metric("Total billed", f"{sub['billed_amount'].sum():,.0f}")
        dc[3].metric("Collection", f"{100 * sub['paid_amount'].sum() / max(sub['billed_amount'].sum(), 1):.1f}%")

    st.subheader("Monthly billed vs paid")
    monthly = (
        claims.assign(month=pd.to_datetime(claims["service_date"]).dt.to_period("M").astype(str))
              .groupby("month")[["billed_amount", "paid_amount"]].sum()
              .reset_index()
    )
    fig = px.bar(monthly, x="month", y=["billed_amount", "paid_amount"], barmode="group")
    st.plotly_chart(fig, width="stretch")


def page_vitals() -> None:
    st.markdown('<div class="hc-label">Real-time monitoring</div>', unsafe_allow_html=True)
    st.title("Live Vital Signs")
    st.caption("Last 24 hours · auto-refreshes every 30 seconds · times shown in Egypt (Cairo).")

    st_autorefresh = None
    try:
        from streamlit_autorefresh import st_autorefresh as _ar  # noqa: WPS433
        st_autorefresh = _ar
    except ImportError:
        pass
    if st_autorefresh:
        st_autorefresh(interval=30_000, key="vital_refresh")
    else:  # dependency-free fallback: reload the page every 30s
        import streamlit.components.v1 as _components
        _components.html(
            "<script>setTimeout(function(){window.parent.location.reload();}, 30000);</script>",
            height=0)

    sql = """
        SELECT TOP (500) *
        FROM dw.vw_vital_signs_minute
        WHERE minute_start_utc >= DATEADD(HOUR, -24, SYSUTCDATETIME())
        ORDER BY minute_start_utc DESC
    """
    vs = _query(sql)
    if vs.empty:
        st.info("No vital sign data in the last 24h.")
        return
    vs["minute_start_utc"] = _to_cairo(vs["minute_start_utc"])
    st.caption(f"Last updated: {_cairo_now().strftime('%Y-%m-%d %H:%M')} (Cairo)")

    c1, c2, c3 = st.columns(3)
    with c1:
        _kpi("Devices reporting", vs["device_id"].nunique())
    with c2:
        _kpi("Anomaly minutes", int((vs["anomaly_event_count"] > 0).sum()))
    with c3:
        active_alerts = vs[vs["anomaly_event_count"] > 0].head(20)
        _kpi("Alerts (last 20)", len(active_alerts))

    st.subheader("Active alerts")
    alerts = (
        vs[vs["anomaly_event_count"] > 0]
            .head(20)[[
                "minute_start_utc", "patient_name", "hospital_name",
                "primary_anomaly_kind", "heart_rate_avg", "spo2_min",
                "systolic_avg", "temperature_c_max",
            ]]
    )
    _show(alerts)

    pick = st.selectbox(
        "Drill-down patient",
        sorted(vs["patient_name"].dropna().unique().tolist()),
    )
    sub = vs[vs["patient_name"] == pick].sort_values("minute_start_utc")
    if not sub.empty:
        fig = px.line(
            sub, x="minute_start_utc",
            y=["heart_rate_avg", "spo2_avg", "systolic_avg"],
            labels={"minute_start_utc": "Time (UTC)", "value": "Reading", "variable": "Vital"},
            title=f"{pick} — last 24 hours",
        )
        _names = {"heart_rate_avg": "Heart rate", "spo2_avg": "SpO₂", "systolic_avg": "Systolic BP"}
        fig.for_each_trace(lambda t: t.update(name=_names.get(t.name, t.name)))
        fig.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                          legend_title_text="", margin=dict(l=0, r=0, t=40, b=0))
        st.plotly_chart(fig, width="stretch", config={"displayModeBar": True})


def _count(view: str) -> int:
    df = _query(f"SELECT encounter_sk FROM {view}" if "encounter" in view
                else f"SELECT * FROM {view}")
    return 0 if df is None else len(df)


def page_home() -> None:
    st.markdown('<div class="hc-label">Executive overview</div>', unsafe_allow_html=True)
    st.title("Network performance")
    try:
        enc = _query("SELECT encounter_date, is_inpatient, is_emergency, is_readmission_30d, "
                     "hospital_name, encounter_class, total_cost_usd FROM dw.vw_encounter_enriched")
        clm = _query("SELECT is_denied, billed_amount, paid_amount, status FROM dw.vw_claim_enriched")
    except Exception as exc:  # noqa: BLE001
        st.error(f"Could not load overview: {exc}")
        return
    if enc is None or enc.empty:
        st.info("No data available.")
        return

    inp = int(enc["is_inpatient"].sum())
    readmit = int(enc["is_readmission_30d"].sum())
    denial = 100 * clm["is_denied"].mean() if clm is not None and len(clm) else 0
    collect = 100 * clm["paid_amount"].sum() / max(clm["billed_amount"].sum(), 1) if clm is not None else 0
    k = st.columns(5)
    k[0].metric("Total encounters", f"{len(enc):,}")
    k[1].metric("Inpatient", f"{inp:,}")
    k[2].metric("30-day readmission", f"{(readmit / inp * 100):.1f}%" if inp else "—")
    k[3].metric("Claim denial rate", f"{denial:.1f}%")
    k[4].metric("Collection rate", f"{collect:.1f}%")

    st.write("")
    left, right = st.columns([3, 2])
    with left:
        st.markdown('<div class="hc-label">Encounter volume — daily</div>', unsafe_allow_html=True)
        ts = enc.groupby("encounter_date").size().reset_index(name="encounters")
        fig = px.area(ts, x="encounter_date", y="encounters")
        fig.update_traces(line_color="#1e6fd9", fillcolor="rgba(30,111,217,.12)")
        fig.update_layout(height=300, margin=dict(l=0, r=0, t=6, b=0),
                          plot_bgcolor="white", paper_bgcolor="white",
                          xaxis_title=None, yaxis_title=None)
        st.plotly_chart(fig, width="stretch")
    with right:
        st.markdown('<div class="hc-label">Encounters by hospital · click a bar to drill</div>',
                    unsafe_allow_html=True)
        byh = enc["hospital_name"].value_counts().reset_index()
        byh.columns = ["hospital_name", "encounters"]
        fig = px.bar(byh, x="encounters", y="hospital_name", orientation="h",
                     custom_data=["hospital_name"])
        fig.update_traces(marker_color="#0f172a",
                          hovertemplate="%{y}<br>Encounters: %{x:,}<extra></extra>")
        fig.update_layout(height=300, margin=dict(l=0, r=0, t=6, b=0),
                          plot_bgcolor="white", paper_bgcolor="white",
                          xaxis_title=None, yaxis_title=None,
                          yaxis={"categoryorder": "total ascending"})
        hosp_evt = st.plotly_chart(fig, width="stretch", on_select="rerun", key="home_hosp")

    picked = None
    try:
        pts = (hosp_evt.get("selection", {}) or {}).get("points", []) if isinstance(hosp_evt, dict) \
            else getattr(getattr(hosp_evt, "selection", None), "points", [])
        if pts:
            cd = pts[0].get("customdata") if isinstance(pts[0], dict) else None
            picked = cd[0] if cd else None
    except Exception:  # noqa: BLE001
        picked = None
    if picked:
        sub = enc[enc["hospital_name"] == picked]
        st.markdown(f'<div class="hc-label">Drill-down — {picked}</div>', unsafe_allow_html=True)
        dc = st.columns(4)
        dc[0].metric("Encounters", f"{len(sub):,}")
        dc[1].metric("Inpatient", f"{int(sub['is_inpatient'].sum()):,}")
        dc[2].metric("Emergency", f"{int(sub['is_emergency'].sum()):,}")
        dc[3].metric("Avg cost", f"${sub['total_cost_usd'].mean():,.0f}")

    st.markdown('<div class="hc-label">Encounter mix &amp; claim status</div>', unsafe_allow_html=True)
    a, b = st.columns(2)
    with a:
        mix = enc["encounter_class"].value_counts().reset_index()
        mix.columns = ["class", "count"]
        fig = px.bar(mix, x="class", y="count", color="class",
                     color_discrete_sequence=px.colors.sequential.Blues_r)
        fig.update_layout(height=260, showlegend=False, margin=dict(l=0, r=0, t=6, b=0),
                          plot_bgcolor="white", paper_bgcolor="white", xaxis_title=None, yaxis_title=None)
        st.plotly_chart(fig, width="stretch")
    with b:
        if clm is not None and len(clm):
            sm = clm["status"].value_counts().reset_index()
            sm.columns = ["status", "count"]
            sm["status"] = sm["status"].str.replace("_", " ").str.title()
            fig = px.pie(sm, names="status", values="count", hole=0.55,
                         color_discrete_sequence=px.colors.sequential.Blues_r)
            fig.update_layout(height=260, margin=dict(l=0, r=0, t=6, b=0), paper_bgcolor="white")
            st.plotly_chart(fig, width="stretch")


HOSP_COORDS = {
    "Cairo Central Hospital": (30.0626, 31.2497),
    "Nile Heart Institute": (30.0900, 31.3600),
    "Giza Specialty Hospital": (29.9800, 31.1200),
    "Alexandria Bayside Medical": (31.2001, 29.9187),
    "Menoufia Regional Medical": (30.5590, 31.0110),
}


def page_map() -> None:
    st.markdown('<div class="hc-label">Network map</div>', unsafe_allow_html=True)
    st.title("Hospital locations")
    st.caption("Each marker is a hospital — hover for detail, click a hospital to drill in.")

    enc = _query("SELECT hospital_name, hospital_governorate, bed_count, total_cost_usd, "
                 "is_readmission_30d, is_inpatient, is_emergency FROM dw.vw_encounter_enriched")
    clm = _query("SELECT hospital_name, is_denied FROM dw.vw_claim_enriched")
    if enc is None or enc.empty:
        st.info("No encounter data.")
        return

    g = (enc.assign(rm=enc["is_readmission_30d"].astype(float))
            .groupby("hospital_name")
            .agg(governorate=("hospital_governorate", "first"),
                 beds=("bed_count", "first"),
                 encounters=("hospital_name", "size"),
                 avg_cost=("total_cost_usd", "mean"),
                 readmit=("rm", "mean"),
                 emergency=("is_emergency", "sum")).reset_index())
    if clm is not None and len(clm):
        d = clm.groupby("hospital_name")["is_denied"].mean().reset_index(name="denial")
        g = g.merge(d, on="hospital_name", how="left")
    else:
        g["denial"] = 0.0
    g["denial"] = (g["denial"].fillna(0) * 100).round(1)
    g["readmit"] = (g["readmit"] * 100).round(1)
    g["avg_cost"] = g["avg_cost"].round(0)
    g["lat"] = g["hospital_name"].map(lambda h: HOSP_COORDS.get(h, (27, 30))[0])
    g["lon"] = g["hospital_name"].map(lambda h: HOSP_COORDS.get(h, (27, 30))[1])

    color_by = st.radio("Colour markers by", ["denial", "readmit", "avg_cost"],
                        horizontal=True, format_func=lambda c: {"denial": "Denial %",
                        "readmit": "Readmission %", "avg_cost": "Avg cost"}[c])

    _cbtitle = {"denial": "Denial %", "readmit": "Readmission %", "avg_cost": "Avg cost ($)"}[color_by]
    fig = px.scatter_mapbox(
        g, lat="lat", lon="lon", size="encounters", color=color_by, text="hospital_name",
        custom_data=["hospital_name", "governorate", "beds", "encounters", "avg_cost", "denial", "readmit"],
        color_continuous_scale="YlOrRd", size_max=24, zoom=6.4,
        center={"lat": 30.45, "lon": 30.98}, height=600)
    fig.update_traces(
        marker=dict(opacity=0.92, sizemin=8),
        textposition="bottom right",
        textfont=dict(size=13, color="#0b2540"),
        hovertemplate=("<b>%{customdata[0]}</b><br>%{customdata[1]} · %{customdata[2]} beds<br>"
                       "Encounters: %{customdata[3]:,}<br>Avg cost: $%{customdata[4]:,.0f}<br>"
                       "Denial: %{customdata[5]:.1f}%  ·  Readmission: %{customdata[6]:.1f}%<extra></extra>"))
    fig.update_layout(mapbox_style="open-street-map", margin=dict(l=0, r=0, t=0, b=0),
                      coloraxis_colorbar=dict(title=_cbtitle, thickness=12, len=0.55, x=0.99))

    event = st.plotly_chart(fig, width="stretch", on_select="rerun", key="hospmap")

    picked = None
    try:
        pts = (event.get("selection", {}) or {}).get("points", []) if isinstance(event, dict) else \
              getattr(getattr(event, "selection", None), "points", [])
        if pts:
            cd = pts[0].get("customdata") if isinstance(pts[0], dict) else None
            picked = cd[0] if cd else None
    except Exception:  # noqa: BLE001
        picked = None

    if picked:
        row = g[g["hospital_name"] == picked].iloc[0]
        st.markdown(f'<div class="hc-label">Selected — {picked}</div>', unsafe_allow_html=True)
        m = st.columns(5)
        m[0].metric("Encounters", f"{int(row['encounters']):,}")
        m[1].metric("Beds", f"{int(row['beds']):,}")
        m[2].metric("Avg cost", f"${row['avg_cost']:,.0f}")
        m[3].metric("Denial %", f"{row['denial']:.1f}%")
        m[4].metric("Readmission %", f"{row['readmit']:.1f}%")
        dx = _query("SELECT primary_icd10_code, primary_diagnosis FROM dw.vw_encounter_enriched "
                    "WHERE hospital_name = ?", (picked,))
        if dx is not None and not dx.empty:
            top = (dx.dropna(subset=["primary_diagnosis"])
                     .groupby(["primary_icd10_code", "primary_diagnosis"]).size()
                     .reset_index(name="count").sort_values("count", ascending=False).head(8))
            st.markdown("**Top diagnoses at this hospital**")
            _show(top)
    else:
        st.caption("👆 Click a hospital marker to see its KPIs and top diagnoses.")

    st.markdown('<div class="hc-label">All hospitals</div>', unsafe_allow_html=True)
    _show(g[["hospital_name", "governorate", "beds", "encounters", "avg_cost", "denial", "readmit"]]
          .sort_values("encounters", ascending=False))


def page_ai() -> None:
    st.markdown('<div class="hc-label">Intelligence</div>', unsafe_allow_html=True)
    st.title("AI Assistant")
    if ai_assistant is None or not ai_assistant.is_configured():
        st.warning("Azure OpenAI is not configured for this deployment (set AOAI_* env vars).")
        return
    if _connect() is None:
        st.info("AI querying needs the live Azure SQL connection (demo mode is read-only Parquet).")

    tab_data, tab_reco, tab_chat = st.tabs(["💬 Ask the data", "💡 Recommendations", "🗨️ Chat"])

    with tab_data:
        st.caption("Ask in Arabic or English — I translate to SQL, run it, and explain the answer.")
        q = st.text_input("Question", placeholder="ما هي أعلى 5 مستشفيات من حيث عدد الحالات؟")
        if st.button("Run", type="primary") and q:
            with st.spinner("Thinking…"):
                try:
                    sql = ai_assistant.nl_to_sql(q)
                    ok, why = ai_assistant.is_safe_sql(sql)
                    st.code(sql, language="sql")
                    if not ok:
                        st.error(f"Blocked unsafe query: {why}")
                    else:
                        df = _query(sql)
                        _show(df)
                        st.markdown(ai_assistant.narrate(q, sql, df.head(20).to_csv(index=False)))
                except Exception as exc:  # noqa: BLE001
                    st.error(f"AI error: {exc}")

    with tab_reco:
        st.caption("KPI-driven operational recommendations.")
        if st.button("Generate recommendations", type="primary"):
            with st.spinner("Analysing KPIs…"):
                try:
                    enc = _query("SELECT is_inpatient, is_emergency, is_readmission_30d, "
                                 "length_of_stay_hours, total_cost_usd FROM dw.vw_encounter_enriched")
                    clm = _query("SELECT is_denied, billed_amount, paid_amount FROM dw.vw_claim_enriched")
                    summary = (
                        f"Encounters={len(enc)}, inpatient={int(enc['is_inpatient'].sum())}, "
                        f"emergency={int(enc['is_emergency'].sum())}, "
                        f"readmit30d={int(enc['is_readmission_30d'].sum())}, "
                        f"avg_LOS_h={enc['length_of_stay_hours'].mean():.1f}. "
                        f"Claims={len(clm)}, denial_rate={100*clm['is_denied'].mean():.1f}%, "
                        f"collection_rate={100*clm['paid_amount'].sum()/max(clm['billed_amount'].sum(),1):.1f}%."
                    )
                    st.caption(summary)
                    st.markdown(ai_assistant.recommendations(summary))
                except Exception as exc:  # noqa: BLE001
                    st.error(f"AI error: {exc}")

    with tab_chat:
        if "chat_hist" not in st.session_state:
            st.session_state.chat_hist = []
        for m in st.session_state.chat_hist:
            st.chat_message(m["role"]).markdown(m["content"])
        if prompt := st.chat_input("Ask about the platform…"):
            st.session_state.chat_hist.append({"role": "user", "content": prompt})
            st.chat_message("user").markdown(prompt)
            with st.chat_message("assistant"):
                try:
                    ans = ai_assistant.chat(st.session_state.chat_hist)
                except Exception as exc:  # noqa: BLE001
                    ans = f"AI error: {exc}"
                st.markdown(ans)
            st.session_state.chat_hist.append({"role": "assistant", "content": ans})


def page_health() -> None:
    st.markdown('<div class="hc-label">Operations</div>', unsafe_allow_html=True)
    st.title("System Health & Monitoring")
    conn = _connect()
    st.metric("Warehouse connection", "🟢 Azure SQL (live)" if conn is not None else "🟡 Demo mode")
    if conn is None:
        st.info("Live monitoring needs the Azure SQL connection.")
        return
    st.subheader("Table row counts")
    try:
        counts = _query(
            "SELECT 'dim_patient' t, COUNT(*) n FROM dw.dim_patient "
            "UNION ALL SELECT 'dim_provider', COUNT(*) FROM dw.dim_provider "
            "UNION ALL SELECT 'dim_hospital', COUNT(*) FROM dw.dim_hospital "
            "UNION ALL SELECT 'dim_payer', COUNT(*) FROM dw.dim_payer "
            "UNION ALL SELECT 'dim_diagnosis', COUNT(*) FROM dw.dim_diagnosis "
            "UNION ALL SELECT 'fact_encounter', COUNT(*) FROM dw.fact_encounter "
            "UNION ALL SELECT 'fact_claim', COUNT(*) FROM dw.fact_claim "
            "UNION ALL SELECT 'fact_vital_signs_minute', COUNT(*) FROM dw.fact_vital_signs_minute")
        _show(counts)
    except Exception as exc:  # noqa: BLE001
        st.warning(f"Count query failed: {exc}")
    st.subheader("Recent ETL loads (dw.load_audit)")
    try:
        audit = _query("SELECT TOP (20) layer, object_name, rows_written, started_at, "
                       "finished_at, status FROM dw.load_audit ORDER BY audit_id DESC")
        _show(audit)
    except Exception as exc:  # noqa: BLE001
        st.warning(f"Audit query failed: {exc}")


PAGE_FUNCS = {
    "Home": page_home,
    "Hospital Operations": page_operations,
    "Revenue & Claims": page_revenue,
    "Live Vital Signs": page_vitals,
    "Egypt Map": page_map,
    "AI Assistant": page_ai,
    "System Health": page_health,
}

_live = _connect() is not None
st.markdown(
    f"""<div class="hc-topbar">
      <div><div class="brand">HealthCare <b>DW</b></div>
      <div class="sub">Hospital-network analytics &middot; Microsoft Azure</div></div>
      <div class="hc-status"><span class="hc-dot" style="background:{'#16a34a' if _live else '#f59e0b'}"></span>
      {'Azure SQL — live' if _live else 'Demo data'}</div>
    </div>""",
    unsafe_allow_html=True,
)

# --- Navigation + filters live here, in the main body (no collapsible sidebar) ---
st.markdown(
    '<div class="hc-nav">📑 Pages <span>— click a tab to switch between pages</span></div>',
    unsafe_allow_html=True,
)
page = st.radio("Page", PAGES, horizontal=True, label_visibility="collapsed", key="page_nav")
_fc1, _fc2, _fc3 = st.columns([3, 3, 4])
with _fc1:
    selected_hospital = st.selectbox("Hospital", hospitals, index=0)
with _fc2:
    date_range = st.date_input(
        "Date range", value=(_cairo_now() - pd.Timedelta(days=90), _cairo_now()))
if isinstance(date_range, tuple) and len(date_range) == 2:
    from_date, to_date = date_range
else:
    from_date, to_date = _cairo_now() - pd.Timedelta(days=90), _cairo_now()
st.divider()

PAGE_FUNCS[page]()
